const version = 'territories-20260923-3';
const response = await fetch(`data.payload.txt?v=${version}`, { cache: 'no-store' });
if (!response.ok) throw new Error(`Territory data module could not be loaded (${response.status}).`);
if (typeof DecompressionStream !== 'function') throw new Error('This browser needs a newer version to open the territory planner.');
const encoded = (await response.text()).trim();
const binary = atob(encoded);
const bytes = Uint8Array.from(binary, character => character.charCodeAt(0));
const source = await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).text();
const moduleUrl = URL.createObjectURL(new Blob([source], { type: 'text/javascript' }));
const module = await import(moduleUrl);
URL.revokeObjectURL(moduleUrl);
export const CCC = module.CCC;
export const TERRITORY_COLORS = module.TERRITORY_COLORS;
export const SOURCE_HINT_BY_HALL = module.SOURCE_HINT_BY_HALL;
export const ASSESSOR_SOURCES = module.ASSESSOR_SOURCES;
export const inferSourceForHall = module.inferSourceForHall;
export const parseSourceFeature = module.parseSourceFeature;
export const normalizeAddressKey = module.normalizeAddressKey;
export const splitStreetSort = module.splitStreetSort;
